### ISSUE TITLE
release build error for 2.0.1 ?

### ISSUE THREAD

**Issue by MarcusE1W** [reznikmm/aarch64-alire-index#2]
Could it be that the release build for alire 2.0.1 was not successful ?

`alr-2.0.1-bin-aarch64-linux.zip` has a size of 12 KB and the previous version has a size of ~9MB.

Once unzipped there is indeed not much more in the release than the license.
Am I overlooking something ?

**Comment by reznikmm** [comment]
Indeed. Sorry for that and thank you for reporting. I make it manually and made a mistake. I've uploaded a fixed files. This time I strip `bin/alr` so the archive is shorter (~6Mb).

**Comment by MarcusE1W** [comment]
Thanks, it works fine now :-)
The only obstacle, but that is not with this package is that alr toolchain does not have a aarch64-linux toolchain.
-- edit
I just notices you provide a FSF aarch64-linux gnat as well. Full service, really.
I need to investigate how to make this all work. Do I understand that correctly, I now need gprbuild and cross-compilers and I have to update the alire index to tie it all together ?
 Thanks a lot.

**Comment by reznikmm** [comment]
You are welcome!

If you install my aarch64-alire-index as described in the README.md then
you will be a to install gnat_native 14.2 and gprbuild for aarch64 linux.
Or you can install gnat/gprbuild from system package manager, but in this
case vscode extension won't detect gnat on Debian/Ubuntu unfortunately.

Сб, 31 серп. 2024, 15:08 користувач MarcusE1W ***@***.***>
пише:

**Comment by MarcusE1W** [comment]
Of course you are right.
Sometimes the problem sits in front of the computer.
This is the first time that I have an Ada toolchain on Archlinux ARM. I have tried to get this done for years now (not very knowledgeable, evidently)
I think you support the ESP32 cross-compiler for aarch64 as well? Is there a chance to add the Arm (microcontroller) cross-compiler as well, to target the Raspberry Pico or the Micro:Bit, or PineTime ?

**Comment by reznikmm** [comment]
> I think you support the ESP32 cross-compiler for aarch64 as well?

ESP32 is work-in-progress. We have only compiler/binutils/gdb, but Ada Runtime is missing.

> Is there a chance to add the Arm (microcontroller) cross-compiler as well

This one is [already here](https://github.com/reznikmm/aarch64-alire-index/blob/main/index/gn/gnat_arm_elf/gnat_arm_elf-14.2.1.toml)!

You can install it with `alr toolchain --select gnat_arm_elf`. For Raspberry Pico there is a great site - https://pico-doc.synack.me/ For Micro:Bit, runtime is included in the `gnat_arm_elf` and there are some examples in Ada_Drivers_Library, but I'm afraid for its older version.
