### ISSUE TITLE
Can't build the Alire hello example on Archlinux ARM

### ISSUE THREAD

**Issue by MarcusE1W** [reznikmm/aarch64-alire-index#3]
Steps:
a) alr get hello
b) cd hello...
c) alr run

This complains about a missing `aarch64-linux-gnu-ar`.
```
ⓘ Building hello=1.0.2/hello.gpr...                                    
gprbuild: unable to locate archive builder "aarch64-linux-gnu-ar"
error: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/home/mmw/prog/ada/tst/hello_1.0.2_5715870b/hello.gpr"] exited with code 4
error: Build failed
```

In `.local/share/alire/toolchains/gnat_native_14.2.1_dc6f8344/bin` the name for `ar` is actually `aarch64-linux-gnu-gcc-ar`

If I link those with `ln -s aarch64-linux-gnu-gcc-ar aarch64-linux-gnu-ar`  I get a different error.
```
Build Libraries
   [gprlib]       Libhello.lexch
   [archive]      libLibhello.a
/home/mmw/.local/share/alire/toolchains/gnat_native_14.2.1_dc6f8344/bin/../lib/gcc/aarch64-linux-gnu/14.2.0/../../../../aarch64-linux-gnu/bin/ar: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
gprlib: call to archive builder /home/mmw/.local/share/alire/toolchains/gnat_native_14.2.1_dc6f8344/bin/aarch64-linux-gnu-ar failed
gprbuild: could not build library for project libhello
error: Command ["gprbuild", "-s", "-j0", "-p", "-P", "/home/mmw/prog/ada/tst/hello_1.0.2_5715870b/hello.gpr"] exited with code 4
error: Compilation failed.
```

**Comment by MarcusE1W** [comment]
Just to add, after linking `ar`, if I compile a simpler example only with `gprbuild` and everything in one folder, no libraries, that works.

**Comment by MarcusE1W** [comment]
After linking `ar` the crate `hangman` works as normal. Maybe the error in `crate`hello is unrelated

**Comment by reznikmm** [comment]
I  Ubuntu/Debian `aarch64-linux-gnu-ar` is a part of [binutils-aarch64-linux-gnu](https://packages.ubuntu.com/noble/amd64/binutils-aarch64-linux-gnu/filelist) package. The same is for [Fedora Linux](https://packages.fedoraproject.org/pkgs/cross-binutils/binutils-aarch64-linux-gnu/fedora-40-updates.html#files). The same is for [ArchLinux](https://archlinux.org/packages/extra/x86_64/aarch64-linux-gnu-binutils/). I don't know why your Arch Linux named it differently.

I googled about `libfl.so.2` on Archlinux. It looks like it is part of [flex](https://archlinux.org/packages/core/x86_64/flex/files/) package. I suggest to install it and try again. I've never tried Archlinux.

**Comment by MarcusE1W** [comment]
Installing `flex` sloved the issue to build hello. Thanks for the help.
